---                                                                                                                                                                                                         
# This playbook deploys a basic application to a VM
- hosts: app1
  become_user: root
  become_method: sudo
  become: yes  

  tasks:
    - name: Install web server
      yum: state=present name={{ item }}
      tags: software
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 8
      with_items:
      - httpd

    - name: Deploy web application
      git:
       repo: 'https://github.com/aludwar/webapp.git'
       dest: /var/www/html
       #version: release-0.22
    
    - name: Start/enable web server
      systemd:
       name: "{{ item }}"
       state: started
       enabled: yes
      with_items:
       - 'httpd'
      tags: software
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 8

    - name: Set firewall rules to allow http/https
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      with_items:
        - https
        - http

    - name: Run unit test on application
      uri:
        url: http://{{ ansible_all_ipv4_addresses }}/index.html
