---

- hosts: all
  tasks:
   - name: Add 'ansible' user for authentication across the inventory
     user:
       name: ansible
       comment: Ansible User
       uid: 2000
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
       password: $6$tn2vIE9oCq.fjQ4r$tUKqkzanIl55aViCecXtOQaqbnKazTni4lDbkOAoSUYt6gjDSC4.XfjfJlHlC7939m88IuyRhCJJ3N7l5SKzD1
       state: present
