---                                                                                                                                                                                                         
# This playbook updates the Tower host.
- hosts: tower.ludwar.ca
  vars: 

  tasks:
    - name: Apply the latest patches and errata to Ansible Tower server
      yum:
        name: 'sos*'
        state: latest
