---                                                                                                                                                                                                         
# This playbook updates the Tower host.
- hosts: all
  become_user: root
  become_method: sudo
  become: yes  
  vars: 

  tasks:
    - name: Apply the latest patches and errata to Ansible Tower server
      yum:
        name: 'sos*'
        state: latest
      delegate_to: localhost
