---
# This playbook contains common plays that will be run on all nodes.

- name: Install chrony [Fedora distro]
  dnf: name=chrony state=present
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22
  tags: chrony

- name: Install chrony [RHEL distro]
  yum: name=chrony state=present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7
  tags: chrony

- name: Install RHEL software needed for the Base role
  yum: state=present name={{ item }}
  tags: software
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7
  with_items:
  - wget
  - net-tools
  - bind-utils
  - bash-completion
  - gpm
  - deltarpm
  - sysstat
  - iotop

- name: Install RHEL software needed for the Base role
  yum: state=present name={{ item }}
  tags: software
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7 and ansible_virtualization_role == guest and ansible_virtualization_type == RHEV
  with_items:
  - rhevm-guest-agent
  
- name: Configure chrony.conf file and restart
  template: src=chrony.conf.j2 dest=/etc/chrony.conf
  tags: chrony
  notify: restart chrony

- name: Enable chrony at boot
  service: name=chronyd state=started enabled=yes
  tags: chrony

- name: Update motd
  template: src=etc.motd dest=/etc/motd
  tags: motd

- name: Add --long-hostname to getty
  lineinfile: dest=/etc/systemd/system/getty.target.wants/getty@tty1.service regexp="^ExecStart=" line="ExecStart=-/sbin/agetty --long-hostname --noclear %I $TERM"  state=present
  tags: getty

- name: Remove annoying system beep
  template: src=nobeep.conf dest=/etc/modprobe.d/nobeep.conf
  tags: physical

- name: Add local user aludwar, enable sudo, unroll home directory - Load/copy script
  template: src=set-aludwar.sh dest=/tmp/set-aludwar.sh mode="u+rwx"   
  tags: user-setup 

- name: Add local user aludwar, enable sudo, unroll home directory - Run script   
  command: bash /tmp/set-aludwar.sh   
  tags: user-setup

- name: Add 'ansible' user for authentication across the inventory
  user:
    name: ansible
    comment: Ansible User
    uid: 2000
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    password: $6$tn2vIE9oCq.fjQ4r$tUKqkzanIl55aViCecXtOQaqbnKazTni4lDbkOAoSUYt6gjDSC4.XfjfJlHlC7939m88IuyRhCJJ3N7l5SKzD1
    state: present

- name: Ensure /etc/sudoers.d/ansible file exists
  copy:
    content: ""
    dest: /etc/sudoers.d/ansible
    force: no
    group: sys
    owner: root
    mode: 0555

- name: Allow ansible user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers.d/ansible
    state: present
    line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


# Copy public SSH keys from all office servers
